### PR TITLE
Mike work text

### PR DESCRIPTION
**Pull request by MikeBrinson**
Guilherme 
I will merge the latest corrected and new text if you agree. -MIKE

### CODE REVIEW

**Comment by guitorri** [comment]
@MikeBrinson, just a few comments. 
Perhaps we should number the labels the same as the figures.
The following is a bit confusing.

```
|image0_EN|
Figure 1 - Qucs built-in resistor model.

.. |image0_EN| image:: _static/en/RFresFig0.png
```

I was also thinking about adding hyperlinks for the figures on the text.

The RFres is a great resource. Isn't it a bit advanced for the _help_ documentation? 
Shall we create another project to replace the tutorial workbook? Just thinking...

**Comment by MikeBrinson** [comment]
Hello Guilherme
Again thanks for your comments.
I will action your point regarding Figure numbers.

At this stage I just added the Rfres doc to the end of Qucs-Help documentation.I have done this as a starting point to test if we could easily port the LateX Tutorialsetc to HTML etc.   I am now sure that this is possible but will require time and effort.
Your suggestion to add a new project for the Qucs Workbook is a good one whichwill allow us to move forward with two documents in parallel.  Regarding the Qucs-help:I will remove RFres from Qucs-Help once the  Workbook project is up and running.  Assoon as you can find time to set up the Workbook project I will continue porting chapters to itand also add lots of new material.   Given a few months to the next release of Qucs shouldallow enough time for preparing a substantial chunk of the new style documentation prior to its first release.

Best wishes.
Mike Mike Brinson

**Comment by guitorri** [comment]
What should we call the project to host the other books? 
qucs-tutorial, qucs-report, qucs-technical ?

**Comment by MikeBrinson** [comment]
Hello Guilherme
A very good question.   I have for a long time not liked the artificial splitthat currently exists.  Most of the currently available documents includeinformation of a very technical/advanced nature.   It seems to me one of 
the best ways forward is to move all material of a beginners/tutorial natureinto the Qucs-Help repo.  As we already aware this needs revising and significantlyexpanding.  Given time it will provide all Qucs users with a large body of 
operational information and a set of typical examples which cover the commonlyused features found in Qucs simulation.  For many Qucs users this may be all theyneed?

Our second level document resource could contain the major body of more advancedsimulation and device modelling information.  This in my opinion should be separate from theexisting Qucs Technical papers which are a valuable resource in their own right.
Could I suggest we follow a practice which is common in other software projects and callthe second level documentation "Qucs-How To's" where each section could contain information on 
advanced simulation techniques, model development/specifications, device and simulation test reports,device parameter extraction techniques and other relevant topics.
Such an approach would give us a three level documentation structure:
1. Qucs-Help, 2. Qucs-How To's and 3. Qucs Technical papers.
This three level structure would still allow the Qucs-How To's to be combined into a"Workbook", for continuity, if needed.
I trust the above makes sense.
Best wishes.
Mike Mike Brinson

mbrin72043@yahoo.co.uk

```
 From: Guilherme Brondani Torri <notifications@github.com>
```

 To: Qucs/qucs-help qucs-help@noreply.github.com 
Cc: MikeBrinson mbrin72043@yahoo.co.uk 
 Sent: Wednesday, 4 February 2015, 7:59
 Subject: Re: [qucs-help] Mike work text (#3)

What should we call the project to host the other books? 
qucs-tutorial, qucs-report, qucs-technical ?—

**Comment by guitorri** [comment]
Merged into the develop branch

**Pull request closed without merging**
